
SUMMARY = "Microsoft Azure Command-Line Tools"
HOMEPAGE = "https://github.com/Azure/azure-cli"
AUTHOR = "Microsoft Corporation <azpycli@microsoft.com>"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=f74e59e099e328d80285c9eba6d4a53f"

SRC_URI = "https://files.pythonhosted.org/packages/a6/73/c6386d1b67a8633772c7bb13e1a2f89e1cec5e0e42b047814686feaf34a4/azure-cli-2.28.0.tar.gz"
SRC_URI[md5sum] = "69376bf398fed01cf37ffd79b54cfef5"
SRC_URI[sha256sum] = "38955531ae6c11694219dded747d330abc40f3a14f316e79f278992b0c9aa411"

S = "${WORKDIR}/azure-cli-2.28.0"

RDEPENDS_${PN} = "python3-chardet python3-idna python3-oauthlib python3-pysocks python3-antlr4-python3-runtime python3-azure-appconfiguration python3-azure-batch python3-azure-cli-core python3-azure-cosmos python3-azure-datalake-store python3-azure-functions-devops-build python3-azure-graphrbac python3-azure-identity python3-azure-keyvault-administration python3-azure-keyvault python3-azure-loganalytics python3-azure-mgmt-advisor python3-azure-mgmt-apimanagement python3-azure-mgmt-appconfiguration python3-azure-mgmt-applicationinsights python3-azure-mgmt-authorization python3-azure-mgmt-batchai python3-azure-mgmt-batch python3-azure-mgmt-billing python3-azure-mgmt-botservice python3-azure-mgmt-cdn python3-azure-mgmt-cognitiveservices python3-azure-mgmt-compute python3-azure-mgmt-consumption python3-azure-mgmt-containerinstance python3-azure-mgmt-containerregistry python3-azure-mgmt-containerservice python3-azure-mgmt-cosmosdb python3-azure-mgmt-databoxedge python3-azure-mgmt-datalake-analytics python3-azure-mgmt-datalake-store python3-azure-mgmt-datamigration python3-azure-mgmt-deploymentmanager python3-azure-mgmt-devtestlabs python3-azure-mgmt-dns python3-azure-mgmt-eventgrid python3-azure-mgmt-eventhub python3-azure-mgmt-extendedlocation python3-azure-mgmt-hdinsight python3-azure-mgmt-imagebuilder python3-azure-mgmt-iotcentral python3-azure-mgmt-iothub python3-azure-mgmt-iothubprovisioningservices python3-azure-mgmt-keyvault python3-azure-mgmt-kusto python3-azure-mgmt-loganalytics python3-azure-mgmt-managedservices python3-azure-mgmt-managementgroups python3-azure-mgmt-maps python3-azure-mgmt-marketplaceordering python3-azure-mgmt-media python3-azure-mgmt-monitor python3-azure-mgmt-msi python3-azure-mgmt-netapp python3-azure-mgmt-network python3-azure-mgmt-policyinsights python3-azure-mgmt-privatedns python3-azure-mgmt-rdbms python3-azure-mgmt-recoveryservicesbackup python3-azure-mgmt-recoveryservices python3-azure-mgmt-redhatopenshift python3-azure-mgmt-redis python3-azure-mgmt-relay python3-azure-mgmt-reservations python3-azure-mgmt-resource python3-azure-mgmt-search python3-azure-mgmt-security python3-azure-mgmt-servicebus python3-azure-mgmt-servicefabric python3-azure-mgmt-servicefabricmanagedclusters python3-azure-mgmt-signalr python3-azure-mgmt-sqlvirtualmachine python3-azure-mgmt-sql python3-azure-mgmt-storage python3-azure-mgmt-synapse python3-azure-mgmt-trafficmanager python3-azure-mgmt-web python3-azure-multiapi-storage python3-azure-storage-common python3-azure-synapse-accesscontrol python3-azure-synapse-artifacts python3-azure-synapse-spark python3-azure-synapse-managedprivateendpoints python3-fabric python3-javaproperties python3-jsmin python3-jsondiff python3-packaging python3-pygithub python3-pynacl python3-pytz python3-scp python3-semver python3-sshtunnel python3-websocket-client python3-xmltodict python3-distro"

inherit setuptools3
